### ISSUE TITLE
One vote allowed per user

### ISSUE THREAD

**Issue by alt113** [alt113/votingApp#6]
@jKh98 

- [x] Each user should only be allowed to cast a single vote per policy/poll/etc...

- **File to target:** `PollFragment.java`
- **Function to target:** `voteUp/voteDown onClickListener`

**Comment by jKh98** [comment]
I managed to do that within the same session
However, you need to add some value in the firebase database for each user that specifies if the user voted. 
I think it can be a dictionary of keys (poll key) and option number (integers)
It can also be as simple as a boolean value  voted or did not vote

**Comment by alt113** [comment]
Thinking it over real quick I find that if we put a boolean in firebase per record that indicates if a vote has been casted or not would restrict other users from voting. Unless we do a new association between users and votes then I think the best thing to do would be to locally saved a key for each user indicating that they have voted in a session (since casting only a single vote is enough to equate an active voting session) @jKh98
